---
- name: add acl configration from console using SmartCS
  hosts: smartcs
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  - ansible_user: "port1"
  - ansible_password: "port1"
  - ansible_port: 9301

  tasks:
  - name: configure access list
    ax_config:
      lines:
        - 10 permit host 172.31.8.41
        - 20 deny any
      parents: ip access-list standard "access ansible host only"
      save_when: changed
  
  - name: set access-list to intarface 
    ax_config:
      lines:
        - ip access-group "access ansible host only" in 
      parents: interface vlan 1
      save_when: changed
