---
- name: 3-2 step3
  hosts: ax
  gather_facts: False
  connection: network_cli
  
  vars:
  - ansible_network_os: ax
  - ansible_become: yes
  - ansible_become_method: enable
  - ansible_become_pass: 'secret2230'
  - ntp:
      server:
        - 10.5.28.115
        - 10.5.31.24
  - snmp:
      community:
        - name: public
          auth: ro
        - name: secret
          auth: rw
  - syslog:
      server:
        - 10.5.28.115
        - 10.5.31.24

  tasks:
  - name: configure ntp server
    ax_config:
      lines:
        - 'ntp client server {{ item }}'
      save_when: changed
    with_items: '{{ ntp.server }}'

  - name: configure snmp community
    ax_config:
      lines:
        - 'snmp-server community {{ item.name }} {{ item.auth }}'
      save_when: changed
    with_items: '{{ snmp.community }}'
  
  - name: configure syslog server
    ax_config:
      lines:
        - 'logging host {{ item }}'
      save_when: changed
    with_items: '{{ syslog.server }}' 
