---
- name: Login from Console using SmartCS
  hosts: smartcs
  gather_facts: no
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - ansible_command_timeout: 60

  tasks:
  - name: login ax2230
    smartcs_tty_command:
      tty: '1'
      recvchar:
      - 'login: '
      - 'Password: '
      - 'AX2230>'
      sendchar:
      - 'alaxala'
      - 'secret2230'
