---
- name: initialzing all setting and log
  hosts: smartcs
  gather_facts: no
  
  vars:
  - ansible_connection: network_cli
  - ansible_network_os: smartcs
  - ansible_command_timeout: 300
  - inituser: 'operator'
  
  tasks:
  - name: "smartcs_tty_command"
    smartcs_tty_command:
      tty: '1'
      cmd_timeout: 180
      custom_response: on
      custom_response_delete_nl: on
      recvchar:
      - 'login:'
      - '> '
      - '# '
      - 'Would you wish to clear SSL key and certificate? (y/n):'
      - 'Restart OK? (y/n):'
      - 'Do you wish to initialize flash memory? (y/n):'
      - 'Do you wish to clear critical-logging? (y/n):' 
      sendchar:
      - '{{ inituser }}'
      - 'enable'
      - 'line console speed 9600 save'
      - 'trace-monitor enable save'
      - 'set exec-timeout 30 save'
      - 'remove mac-authentication mac-address -all -f'
      - 'commit mac-authentication -f'
      - 'remove web-authentication user -all -f'
      - 'clear web-authentication html-files -f'
      - 'clear web-authentication ssl-crt'
      - 'y'
      - 'show license'
      - 'remove wol-device name all -f'
      - 'commit wol-device -f'
      - 'remove wol-authentication user all -f'
      - 'commit wol-authentication -f'
      - 'clear ip dhcp snooping binding'
      - 'clear ip dhcp server statistics'
      - 'reload'
      - 'y'
      - 'operator'
      - 'enable'
      - 'format flash__NOWAIT__:5'
      - 'y'
      - 'clear critical-logging'
      - 'y'
      - 'reload'
      - 'y'
